version: '3.5'

services:
  postgres:
    container_name: nest-jwt
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      TZ: 'Asia/Ho_Chi_Minh'
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres: